version: '3.3'

networks:
  default:
    external:
      name: devmexa

services:
  mexa-analysis:
    container_name: devmexaanalysis
    image: vijayjeyam/devmexaanalysis
    ports:
      - "9036:9035"
    environment:
      - SPRING_APPLICATION_NAME=analysis
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_LABEL=main
      - CLOUDCONFIG_HOST=devcloudconfig
      - CLOUDCONFIG_PORT=9065
      - CLOUDCONFIG_USER=psc
      - CLOUDCONFIG_PASSWORD=psc123$
    volumes:
      - 'my-analysis:/home/devserver/mexa'

volumes:
  my-analysis:
    driver: local
