version: '3.3'

networks:
  default:
    external:
      name: prodmexa

services:
  mexa-analysis:
    container_name: prodmexaanalysis
    image: vijayjeyam/prodmexaanalysis
    ports:
      - "9035:9035"
    environment:
      - SERVER_PORT=9035
      - SPRING_APPLICATION_NAME=analysis
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_LABEL=main
      - CLOUDCONFIG_HOST=prodcloudconfig
      - CLOUDCONFIG_PORT=9065
      - CLOUDCONFIG_USER=psc
      - CLOUDCONFIG_PASSWORD=psc123$
      - EUREKA_HOST=prodmexaeureka
      - EUREKA_PORT=9085
      - EUREKA_CLIENT_ENABLED=true
      - DB_HOST=prodenochmysql
      - DB_PORT=3306
      - DB_NAME=psc
      - DB_USERNAME=psc
      - DB_PASSWORD=psc123$
    volumes:
      - 'my-analysis:/home/devserver/mexa'

volumes:
  my-analysis:
    driver: local
