spring.application.name=${SPRINGAPPLICATION_NAME}
spring.profiles.active=${SPRINGPROFILE}
spring.cloud.config.label=${SPRINGCLOUD_LABLE}

spring.config.import=configserver:http://${CLOUDCONFIG_HOST}:${CLOUDCONFIG_PORT}

spring.cloud.config.username=${CLOUDCONFIG_USER}
spring.cloud.config.password=${CLOUDCONFIG_PASSWORD}

management.endpoints.web.exposure.include=health,info,refresh
endpoints.env.keys-to-sanitize=false

logging.level.root=INFO
