spring.application.name=analysis
server.port=8086

spring.profiles.active=prod
spring.cloud.config.label=main
spring.config.import=optional:configserver:http://localhost:9065/
spring.cloud.config.username=psc
spring.cloud.config.password=psc123$

management.endpoints.web.exposure.include=health,info,refresh,prometheus

spring.datasource.url=jdbc:mysql://localhost:3306/psc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=psc
spring.datasource.password=psc123$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.allow-bean-definition-overriding=true

analysis.feature-enabled=true
analysis.query.xml.location=classpath:queries/analysis-queries.xml
analysis.summary.default-pass-percentage=50.0
analysis.summary.exclude-qtypes=MOCKTEST,COMPETITION

logging.level.root=INFO
